README.md
https://github.com/geex-arts/django-jet/issues/280#issuecomment-547018214
=> remove unsupported Django-jet

README.md
I'm sure @pydanny and @audreyr make more commission from their own site over Amazon.
=> Link direct to two scoops press

README.md
Add books by @archatas and @zenx
=> Add two Django 3 books

README.md
- Saleor is the eCommerce platform with the latest technologies that I have ever found.
=> Add a Graphql-based Ecommerce Platform

README.md
Added django-cleanup to auto delete files from filesystem or s3 on file/image delete.
=> Added Django Cleanup

README.md
- Added `django-guid`. https://github.com/JonasKs/django-guid  
- Added `django-swagger-tester`. https://github.com/sondrelg/django-swagger-tester  
- Sorted the Django list to be alphabetical.
=> Added two packages and sorted the list

README.md
This PR adds the Django Styleguide to this list of awesome repos. The Django Styleguide contains a great series of advices and best practices about writing APIs, testing, celery, models and business logic for long living and easy to maintain django projects.
It is open for discussion and new ideas in the Issues tab.
=> Add Django Styleguide

README.md
=> Add django-oscar

README.md
=> Add django-polymorphic

README.md
I built this project as a place to collect cool functioning projects built with Django. The reason I wanted to build this is to answer a popular question: "What can be built with Django?".
=> Adding Built with Django open source project

README.md
Tooting my own horn a bit here, but none of these other boilerplates worked for me so I made my own. Hopefully as useful for others as it has been for me!
=> Add django-docker-heroku-template

README.md
Added impostor. Impostor is a Django application which allows staff members to login as a different user by using their own username and password.
=> Add impostor

README.md
=> add django-robots

README.md
=> add django-constance

README.md
=> add django-cas-ng

README.md
=> add django-summernote

README.md
Used the 'Testing' section, got a proposal for a different one or is it fine?
=> Add django-google-optimize

README.md
Github - https://github.com/vitalik/django-ninja
Documentation - https://django-ninja.rest-framework.com
=> Add django-ninja

README.md
Hello. For your consideration, I added djenv, which is a library that allows you to configure Django settings with environmental variables.  It automatically deciphers what environmental variables corresponds to what Django settings.  It also automatically casts the environmental variables into the right type.  Thank you for your time.
=> Added djenv

README.md
HyperKitty - A web interface to access GNU Mailman v3 archives.
=> add HyperKitty

README.md
I'm quite surprised to see that it hasn't been mentioned here!
=> Add django-configurations

README.md
reopen https://github.com/wsvincent/awesome-django/pull/76
updated to meet requirements https://github.com/cobusc/django-protected-media/issues/2
=> django-protected-media

README.md
For your consideration
When looking for an app that kept track of model history by user, ive found this to be the easiest to implement.
=> django-easy-audit

Gemfile.lock, README.md, _includes/header.html
I added Fork Me ribbon from https://github.blog/2008-12-19-github-ribbons/
=> fixes #98 : Added Fork me on GitHub

README.md
=> :pencil: fix django-summernote section

README.md
I realize I'm biased since one of these projects is mine :), but I think that it would be great if Django developers realize that there are libraries which enhance Django and let you create a modern website without giving up all of the benefits of Django. All of these projects achieve that goal which I think is pretty awesome!
=> Add section for full-stack frameworks

README.md
Totally biased here because it's my own project.
Launchr is a specialized starter template for SaaS web apps. It implements the full payment flow, subscription management, user authentication and a couple of other things that are needed for a SaaS.
=> Add the launchr template to the boilerplate section

README.md
Events and calendar apps can leverage an old spec ical for complex repetition logic. 
https://tools.ietf.org/html/rfc5545
https://github.com/django-recurrence/django-recurrence
=> Add django-recurrence

README.md
Here is [tutorial](https://thesaintraphael.medium.com/customizing-admin-panel-in-django-c3c64fbcb347) about django-jet-reboot
=> Add django-jet-reboot

README.md
https://adamj.eu/tech/2021/07/08/django-3.2-update-for-speed-up-your-django-tests-released/
=> Bump SUYDT to Django 3.2 section

README.md
https://www.dynaconf.com/django/
=> Add Dynaconf

README.md
I wouldn't claim my tutorials are all "regular".
=> Update description of my site

README.md
Appliku it is awesome because it allows server setup and app deployment on your own cloud servers without the need of DevOps knowledge
=> Added Appliku PaaS

README.md
Hi Will and Jeff,
just stumbled across this easy to use and powerful toolkit for fast development of CRUD applications based on Django.
Take a quick look at the gif at the github project to see a demo how easy it is to create pages and forms.
=> Add iommi toolkit

README.md
This thing is awesome and deserves more attention.
=> Add django-data-browser

README.md
Hey ,
I have added a DRF API Logger. It is API Logger for your Django Rest Framework project.
https://github.com/vishalanandl177/DRF-API-Logger
Thank you
=> Added `DRF API Logger`

README.md
Looks like you have a few of these already, but this one has been my favorite for a while. Still actively maintained but it's not on GitHub (the one on GitHub looks like a really old fork). Just thought I would mention it!
=> Add django-impersonate

README.md
The Django discord server is a game changer,  newbies can get instant help, django developers can get advice from each other, and have a fun time!
That's why I think it should be added  to the the "Awesome Django List".
=> Add the official django discord community link.

README.md
Consistently applied oxford commas, and added a hyphen to the word "full featured"
=> Small grammar fixes in readme.md

README.md
https://github.com/fabiocaccamo/django-treenode
=> Add `django-treenode`.

README.md
https://github.com/fabiocaccamo/django-extra-settings
=> Add `django-extra-settings`.

README.md
https://github.com/fabiocaccamo/django-redirects
=> Add `django-redirects`.

README.md
https://github.com/fabiocaccamo/django-maintenance-mode
=> Add `django-maintenance-mode`.

README.md
https://github.com/fabiocaccamo/django-colorfield
=> Add `django-colorfield`.

README.md
https://github.com/fabiocaccamo/django-freeze
=> Add `django-freeze`.

README.md
https://github.com/raagin/django-streamfield
=> Add `django-streamfield`.

README.md
Adds `django-bleach` to the forms section, addressing #195
=> Added django-bleach [#195]

.gitignore, README.md
=> 🚜  Split model fields tests

README.md
Pyinstrument has a [1 line integration with django](https://pyinstrument.readthedocs.io/en/latest/guide.html#profile-a-web-request-in-django) allowing profiling the code line by line. It allows profiling html and api views. It also has an intuitive interface and is quite simple to interpret it's results
=> Add pyinstrument

README.md
---
title: django-docker-template
assignees: ''
---
1. **Project Name:** django-docker-template
2. **Project URL:** https://github.com/amerkurev/django-docker-template
3. **Description:** Dockerized Django with Postgres, Gunicorn, and Traefik (with auto renew Let's Encrypt)
2 months
This is a project template, it doesn't need any versions.
4. **Are you the author or are you …
=> Add django-docker-template

README.md
Weblate is a copylefted libre software web-based continuous localization system, used by over 2500 libre projects and companies in more than 165 countries.
https://github.com/WeblateOrg/weblate
=> Add weblate

README.md
Added Django for Everybody course, and Harvard's CS50W webdev course.
---
assignees: ''
---
3. **Description:** _(Please provide a brief description of the project.)_
_(Please provide an approximate duration in months or years.)_
_(Please provide the number of releases, or link to the project's release …
=> Added DJ4E and CS50W courses in Education

README.md
---
title: "[NEW] drf-spectacular"
assignees: ''
---
1. **Project Name:**  drf-spectacular
3. **Project URL:** https://github.com/tfranzel/drf-spectacular
4. **Description:**  Sane and flexible OpenAPI 3 schema generation for Django REST framework. 
3 years
https://github.com/tfranzel/drf-spectacular/releases
5. **Are you the author or are you submitting the project on behalf of a …
=> [NEW] drf-spectacular

README.md
1. **Project Name:** django-ace
2. **Project URL:** https://github.com/django-ace/django-ace
3. **Description:** Django-ace-editor is an implementation of the ajax.org Ace editor as a form widget. 
11.5 years
**ace**: 50
**django-ace**: 15
Just using this project.
This project enables users to quickly add ACE editor widgets to Django Admin.
[ACE …
=> Add ACE Editor

README.md
---
name: python-socketio
about: Integration Django with Socket.io
title: python-socketio
labels: new python package
assignees: ''
---
1. **Project Name:** python-socketio
2. **Project URL:** [GitHub Repository](https://github.com/miguelgrinberg/python-socketio)
3. **Description:** Python implementation of the Socket.IO_ realtime client and server.
_(Please provide an approximate duration in months or years.)_
- Approximately 8 years.
_(Please provide the number of releases, or link to …
=> Update README.md to add python-socketio

README.md
Adds django-allauth-ui which enhances the django-allauth templates.
---
title: django-allauth
assignees: ''
---
1. **Project Name:**  django-allauth-ui
2. **Project URL:** https://github.com/danihodovic/django-allauth-ui
3. **Description:** Enhances the django-allauth templates.
2. **How long has the project been maintained?** 2 years.
3. **How many releases has it had if it's a library or package?** ~30 releases on PyPI https://pypi.org/project/django-allauth-ui/#history
4. **Are you the …
=> Add django-allauth-ui

README.md
Updates the domain name, and splits out our website, dev docs, and user docs.
=> Update Wagtail links

README.md
1. curlylint
1. **Project Name:** curlylint
2. **Project URL:** <https://www.curlylint.org/>
3. **Description:** _Experimental HTML templates linting for Jinja, Nunjucks, Django templates, Twig, Liquid._
2. django-components
1. **Project Name:** django-components
2. **Project URL:** <https://github.com/EmilStenstrom/django-components/>
3. **Description:** _A way to create simple reusable template components in Django._
3. django-template-partials
1. **Project Name:** django-template-partials
2. **Project URL:** <https://github.com/carltongibson/django-template-partials/>
3. **Description:** _Reusable named inline partials for the Django Template Language._
4. djhtml
1. **Project Name:** djhtml
2. **Project URL:** <https://github.com/rtts/djhtml>
3. **Description:** _Django/Jinja template …
=> [NEW] Packages for a new Templates section

README.md
---
name: Add django-classy-settings
assignees: ''
---
1. **Project Name:** django-classy-settings
2. **Project URL:** https://django-classy-settings.readthedocs.io/en/latest/
3. **Description:** _(Please provide a brief description of the project.)_
Class based settings to keep your environments in order, with easy access to typed environment variables.
10 years
20
5. **Are …
=> Add django-classy-settings

README.md
As updated today: https://adamj.eu/tech/2024/01/17/byddx-update/
=> Update Boost Your Django DX supperted Django version

README.md
---
title: "Add PIKU to PAAS section"
assignees: ''
---
1. **Project Name:** PIKU PAAS
2. **Project URL:** https://github.com/piku/piku
3. **Description:** A PAAS similar to DOKKU but better :)
At least 3yrs
They have had 691 commits
A simple PAAS like Dokku but even …
=> Add piku to PAAS section.

README.md
---
title: django-webhook
assignees: ''
---
1. **Project Name:** django-webhook
2. **Project URL:** https://github.com/danihodovic/django-webhook
3. **Description:** 
A plug-and-play Django app for sending outgoing webhooks on model changes.
Django has a built-in signal system which allows programmers to schedule functions to be executed on model changes. django-webhook leverages the signal system together with Celery to send HTTP requests when models change.
2. **How long has the project been …
=> Add django-webhook

README.md
Add django-typer app and include a link to click.
---
name: Add django-typer
title: "[NEW] django-typer"
---
1. **Project Name:** django-typer
2. **Project URL:** https://github.com/bckohan/django-typer
Provides a TyperCommand class that extends from BaseCommand and allows devs to define their Django management commands using type hints via the [Typer library](https://typer.tiangolo.com/). Includes a management command installer that adds shell tab completion support to both normal Django commands and TyperCommands for bash, zsh, fish and powershell.
----
Please answer the following questions about the project you are submitting. This will help us evaluate if the project should be included in the Awesome …
=> Add django-typer

README.md
Django Q2 is a fork of Django Q. Big thanks to Ilan Steemers for starting this project. Unfortunately, development has stalled since June 2021. Django Q2 is the new updated version of Django Q, with dependencies updates, docs updates and several bug fixes. Original repository: https://github.com/Koed00/django-q
---
---
django-q2
https://github.com/django-q2/django-q2
Django Q2 is a fork of Django Q. Big thanks to Ilan Steemers for starting this project. Unfortunately, development has stalled since June 2021. Django Q2 is the new updated version of Django Q, with dependencies updates, docs updates and several bug …
=> update django-q to django-q2

README.md
1. **Project Name:** django-pony-express
2. **Project URL:** https://pypi.org/project/django-pony-express/
3. **Description:** Similar to class-based view in Django core, this package provides a neat, DRY and testable (!) way to handle your emails in Django.
----
v1.0 was released in May 2023, but the code used to live in the [ambient-toolbox package](https://github.com/ambient-innovation/ambient-toolbox/) and was [created (and maintained)](https://ambient-toolbox.readthedocs.io/en/latest/features/changelog.html) since 2021-02-25.
3. **How many …
=> Suggestion: django-pony-express

README.md
1. **Project Name:** django-unfold
2. **Project URL:** https://github.com/unfoldadmin/django-unfold
3. **Description:** Modern Django admin theme for seamless interface development 
----
2. **How long has the project been maintained?** 
18 months
[PyPI releases](https://pypi.org/project/django-unfold/#history)
Unfold provides a modern UI for the default Django administration panel by using TailwindCSS, Alpine.js, and HTMX. Except of visual improvements, Unfold offers useful utilities for building admin panels like advanced sidebar configuration, WYSIWYG, numeric & datetime filters, …
=> Add django-unfold

README.md
1. django-migration-zero
2. https://github.com/ambient-innovation/django-migration-zero/
Holistic implementation of "migration zero" pattern for Django covering local changes and in-production database adjustments.
----
First release came out in October 2023.
https://pypi.org/project/django-migration-zero/#history
Neat alternative to squashmigrations in …
=> Suggestion: django-migration-zero

README.md
1. **Project Name:** django-content-settings
2. **Project URL:** https://github.com/occipital/django-content-settings
3. **Description:** _offering users the ability to easily create and manage editable variables directly from the Django admin panel. What sets this module apart is its ability to handle variables of any type without restricting their complexity. Thanks to an integrated caching system, these variables can be used efficiently in code, irrespective of their complexity._
for more than a year, but for a long time it was part of an internal …
=> Add: django-content-settings

README.md
1. **Project Name:** Djangonaut Space
2. **Project URL:** https://djangonaut.space
Free peer-mentoring program for the Django community to launch people into the universe of open source contributions.
----
Djangonaut Space …
=> Add Djangonaut Space

README.md
add django-role-permissions and django-rules
=> add Permissions section

README.md
Added some of the latest Books from https://djangobook.com/ Maybe a link to https://djangobook.com/ would also fit on top of the section?
I did not filled out the form below, as I did not submit a project only some books which were not listet but I found on https://djangobook.com/
Hope this is ok.
Kind regards
Harald Lux 
---
---
_(Please provide a brief description of the project.)_
----
**Note:** If your project is only a few months old or has under …
=> Added Book Entries

README.md
---
title: "[NEW] OpenContracts"
---
1. **Project Name:** OpenContracts
2. **Project URL:** https://github.com/JSv4/OpenContracts
3. **Description:** Enterprise-grade document analytics platform that combines automated PDF parsing, vector embeddings, and LLM integration with manual annotation capabilities to enable sophisticated document management and extraction of insights at scale. Apache-2 Licensed, it provides several key features:
----
3 years
https://github.com/JSv4/OpenContracts/releases
6. **Are you the author or are you submitting the project on behalf …
=> [NEW] OpenContracts

README.md
---
title: "Django-Classy-Doc"
---
1. **Project Name:** Django-Classy-Doc
2. **Project URL:** https://github.com/nanuxbe/django-classy-doc
Create a documentation site in the style of [CCBV](https://ccbv.co.uk) and [CDRF](https://cdrf.co) but for your own project code.
----
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and then consider a submission at a later …
=> Add Django-Classy-Doc

README.md
1. **Project Name:** Local Django Communities
2. **Project URL:** https://www.djangoproject.com/community/local/
The page is a good overview of all local Django events / groups.
----
5-10 years?
3. **How many releases has …
=> Add Local Django Communities Page

README.md
1. **Project Name:** DjangoCongress JP
2. **Project URL:** https://djangocongress.jp/
This is the largest Django conference in Japan.
----
I think 5+ years? …
=> Add DjangoCongress JP

README.md
add django-auto-prefetch
---
title: "[NEW] django-auto-prefetch"
---
1. django-model-prefetch
2. **Project URL:** https://github.com/tolomea/django-auto-prefetch
4. **Description:**
Automatically prefetch foreign key values as needed
----
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and then consider a submission at a later date when it has gained more visibility and community …
=> Add django-auto-prefetch to Models section

README.md
Add anymail to mailing section
Add Ruff to python section
---
---
_(Please provide a brief description of the project.)_
----
1. **Is the …
=> Add anymail and ruff

README.md
1. **Project Name:** Django Day Copenhagen
2. **Project URL:** https://www.youtube.com/@djangodanmark
It’s the YouTube channel for an established Django event :)
----
6 years
3. **How many releases has it had if it's a …
=> Add Django Day Copenhagen Youtube channel

README.md
2. **Project URL:** https://github.com/realOrangeOne/django-tasks
An implementation and backport of background workers and tasks in Django, as defined in [DEP 0014](https://github.com/django/deps/blob/main/accepted/0014-background-workers.rst).
---- …
=> Add django-tasks

README.md
1. **Project Name:** Baserow
2. **Project URL:** https://gitlab.com/baserow/baserow
Baserow is a free and open-source no-code database tool and Airtable alternative. Built with Django and Vue.js, it provides a user-friendly interface for creating and managing databases without coding knowledge while maintaining the flexibility and power of a professional database system.
----
Active development for over 4 years with regular updates and strong community engagement.
Multiple stable releases with version 1.19.1 being the latest as of early 2024. Regular release cycle with both feature updates and bug fixes.
4. **Are you the author …
=> Add Baserow 

README.md
---
title: "Blaze.horse"
---
1. Blaze.horse
2. https://github.com/piepworks/blaze-starter | https://blaze.horse
3. A starter kit I created for myself to be able to hit the ground running quickly when starting a new Django project.
----
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and then consider a submission at a later date when it has gained more visibility and community …
=> Add Blaze.horse

README.md
---
name: Add a new podcast
about: Suggest a new Django podcast for the Awesome Django list
title: "[NEW] Django Brew"
---
1. **Project Name:**
Django Brew
2. **Project URL:**
https://djangobrew.com/
Django Brew is an awesome podcast by existing Django community members. Their discussions are fun and educational. It presents another side of the Django community in podcast form!
----
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and then consider …
=> Add Django Brew :coffee: podcast

README.md
Moved to general category as per previous discussion, and updated the URL to be the new one.
=> Update README.md, iommi

README.md
---
name: django-removals
title: [NEW] "django-removals"
---
1. **Project Name:** django-removals
2. **Project URL:** https://github.com/ambient-innovation/django-removals/
This package will throw [Django system checks](https://docs.djangoproject.com/en/dev/topics/checks/) warnings for all known removals from Django v1.0 to today.
----
Please answer the following questions about the project you are submitting. This will help us determine whether it should be included in the Awesome Django list.
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and …
=> [NEW] "django-removals"

README.md
---
title: "[NEW] django-admin-collaborator"
---
1. **Project Name:**
django-admin-collaborator
2. **Project URL:**
https://github.com/brktrlw/django-admin-collaborator
Real-time collaboration features for the Django admin interface using Django Channels and Redis. Includes live edit locks, user presence indicators, WebSocket chat, and attention request system.
----
_(First public release: April 2025)_
Approximately 2.5 months (since April 2025).
20+ releases  
[Release history](https://pypi.org/project/django-admin-collaborator/#history)
4. …
=> Add django-admin-collaborator to Admin section

README.md
---
name: Update Open Source Projects section
about: Suggest removing the Django-CRM  project from the Awesome Django list due to its closure.
title: "Removing the Django-CRM"
---
The proposed update is due to the fact that two months ago the Django-CRM project announced [its closure](https://github.com/MicroPyramid/Django-CRM) and discontinuation of support ("... *No further updates will be made to this repository.*").
The author started a new project without using Django ("*Development will continue in the new SvelteKit-based repository.*").
=> Update Open Source Projects section

README.md
---
title: "[NEW] Wireup"
---
1. **Project Name:** Wireup
2. **Project URL:** https://github.com/maldoinc/wireup // https://maldoinc.github.io/wireup/latest/integrations/django/
3. **Description:** 
Wireup is a performant, concise and easy-to-use Dependency Injection container with support for modern Python features such as async, typing, generators with first-class support for Django.
----
Please answer the following questions about the project you are submitting. This will help us determine whether it should be included in the Awesome Django list.
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django …
=> Add Dependency Injection section and add Wireup to it

README.md
---
title: "Update link to Blaze.horse"
---
> **⚠️ Important:** Deleting this template or ignoring its requirements will most likely result in your pull request being closed without review. Please take the time to fill out all sections completely.
1. **Project Name:** BH2
2. **Project URL:** https://codeberg.org/trey/bh2
A new version of the old Blaze.horse starter kit.
----
Please answer the following questions about the project you are submitting. This will help us determine whether it should be included in the Awesome Django list.
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome …
=> Update link to new version of Blaze.horse
