wsvincent/awesome-django

README.md

Hey - thanks for providing this amazing list. It is one of the most helpful resources anyone could find about Django. I noticed though that celery is not mentioned - it is assumed being the standard provider so I thought I would add it.

Add celery task queues

---

README.md

Stronghold is a very small and easy to use django app that makes all your Django project default to require login for all of your views.
Not sure if this justifies a new category `Auth`.

Add Django-stronghold

---

README.md

Adds [django-dramatiq](https://github.com/Bogdanp/django_dramatiq) that is a Django app that integrates [dramatiq](https://dramatiq.io/) - A background task processing library for Python with a focus on simplicity, reliability and performance.
We're using this on production for ~1 year.

Add django-dramatiq

---

README.md

This cookiecutter extends the awesome pydanny one, but adds Vue support in a unique way that allows mixed usage of Django Templates and Vue Single File Components (SFCs).  An easy way to bootstrap a flexible Vue + Django project.
Disclaimer: my own repo.

add cookiecutter-vue-django

---

README.md

I've just created a new section named _Editors_ in order to store all WYSIWYG editors. It includes the following packages. (**These items are the most rated packages in this category**)
- django-ckeditor 
- django-markdownx
- django-markdown-editor
- django-wysiwyg-redactor
- django-business-logic
- django-quill-editor
These packages added to the Python Packages section.
- faker (One of the coolest fake data generators that matches with Django ORM very well)
- python-decouple (A tool to store environment variables for security configurations)

Editors category created + some packages added to Python Packages section

---

README.md

Add Django-admin-interface app to the list, enables users to easily customize the admin interface.

Add Django-admin inteface to the list

---

README.md

SEO is an important aspect of web dev, and many people does not know how it "works", so I think adding a new category is appropriate.
Django Check SEO is a tiny package that will parse the html content of the pages of a Django website, and that will display the list of common mistakes/good practices relative to the content of the page.

Create SEO category and add django-check-seo to it

---

README.md

hetzner is a slightly more cheap and reliable alternative to DigitalOcean, with the servers being based in Europe rather than US

Add hetzner to IaaS list

---

README.md

Django admin's list_display is a powerful tool for adding columns to a model's admin panel. One weakness is that unlike list_filters, list_display cannot traverse relationships. I.e., given Person has_a Employer, `employer__name` doesn't work in list_display.
django-related-admin enables foreign key attributes in list_display with '__'

add django-related-admin

---

README.md

[Healthchecks](https://github.com/healthchecks/healthchecks) is an actively developed open source project based on Django 3.1. Browsing the source is a great way to see an example of a real world Django application, especially for people new to Django as the project is not as complex as something like [Zulip](https://github.com/zulip/zulip).

Add Healthchecks to Open Source Projects

---

README.md

This PR includes the link to new "Task Queue" i.e. Django-celery-beat, which helps to schedule task through the admin panel and can be stored in database.

feat: Django celery beat task scheduler

---

README.md

Old link 404'd to old "Django Crash Course" URL.  Fixed to go to new "Wedge of Django" on feldroy.com

Fix Wedge of Django link

---

README.md

I've been running the DJ Checkup website for the last couple of years and have run close to 6000 security scans over deployed Django websites. I took this over from the Pony Checkup site after Sasha decided to close it down.
In my opinion, this would make a good addition to the Security section. 
Cheers - Stuart.

Add DJ Checkup

---

README.md

I'm not sure if we should remove this section or just add a warning
Django 2.2 support ended a month ago on April 11, 2022
https://www.djangoproject.com/download/#unsupported-versions
* https://github.com/wsvincent/awesome-django/issues/169

Remove Django 2.2 section

---

README.md

We're an open source feature flagging platform built on top of Django and Django Rest Framework. Would love to be included in this repo!

Add Flagsmith

---

README.md

[django-admin-sortable2](https://github.com/jrief/django-admin-sortable2) is the most popular sorting library for the Django admin.
531 stars, 120k downloads/month.
Competitors
* [django-admin-sortable](https://github.com/jazzband/django-admin-sortable): 510 stars, 50k downloads/month.
* [django-orderable](https://github.com/django-ordered-model/django-ordered-model): 592 stars, 87k downloads/month.

django-admin-sortable2

---

README.md

29 stars, 0 forks, 13 commits. How could it have been included in the first place?

remove danieljdufour/djenv

---

README.md

I didnt know if it goes well under the header **APIs** (next to graphene-django) or **General** (next to django-filter).
But I figured this is especially useful to people using `graphene-django` hence I put this under it in **APIs**. Let me know if it needs to be put in somewhere else. 
resolves #225

Add graphene-django-filter to README.md

---

README.md

1. **Project Name:** ReactPy
2. **Project URL:** https://github.com/reactive-python/reactpy
3. **Description:** It's React, but in Python.
Fix #213 
3.5 years
ReactPy = 93 releases.
ReactPy-Django = 24 releases.
This is a Python port of ReactJS. We tried to keep the syntax as similar to ReactJS as possible, while still being written in pure Python. All ReactJS design …

Add ReactPy

---

README.md

It feels it belongs better under the `Static Assets` section, or WDYT?

Move whitenoise to a more logical place in the file

---

README.md

1. **Project Name:**  `django-guest-user`
2. **Project URL:** https://github.com/julianwachholz/django-guest-user
3. **Description:** Allow visitors to interact with your site like a temporary user ("guest") without requiring registration. They can "convert" to a regular user account at any time without losing data.
About two years.
[12 releases so far](https://pypi.org/project/django-guest-user/0.5.5/#history)
4. **Are you the author or are you submitting the project on behalf of a …

Add django-guest-user

---

README.md

1. **Project Name:** django-celery-results
2. **Project URL:** https://github.com/celery/django-celery-results
3. **Description:** This is a package that integrates Celery Results with Django ORM and Django Admin interface.
----
~7.5 years
[12 releases](https://github.com/celery/django-celery-results/releases) & [19 tags](https://github.com/celery/django-celery-results/tags)
Just using it.
It makes managing and introspecting Celery results easy with Django ORM and Admin integration.

Add Django Celery Results

---

README.md

I noticed there is currently no section that pertains to i18n at all, so as a resident of a country with 4 national languages I felt compelled to add it. :)
I've populated the internationalization category with some of the most commonly used packages that are well established. There are others with many hundreds stars but these projects haven't seen any activity in over 2 years.
- django-localflavor - Self-explanatory as a previous Django core module.
- django-modeltranslations - The i18n project with the most Github stars, using a registry to create migrations and even allows translating third party models.
- django-modeltrans - A modern solution using a single JSONField to store translated values and using virtual fields to access them (my personal favorite as it's much more lightweight …

Add i18n section

---

README.md

The old link redirects to "https://www.rossp.org/blog/farewell-djangosites/?utm_source=djangosites.org&utm_medium=redirect&utm_campaign=djangosites-farewell" which currently reads: "Farewell, Djangosites Time for something new to take it’s place."
The resource is no longer valid.
---
name: Remove link which no longer works.
N/A
N/A
N/A
People don't get taken to a …

Removed 'Django Sites' as it no longer exists.

---

README.md

---
---
Adds a monitoring section with two initial entries:
- Django-prometheus
- Django-mixin
https://github.com/korfuri/django-prometheus
https://github.com/adinhodovic/django-mixin
4. **Description:**
_(Please provide a brief description of the project.)_
Django-prometheus: Export Django monitoring metrics for Prometheus.io
Django-mixin: Monitoring mixin for Django-prometheus. A set of Grafana dashboards and Prometheus rules for Django.
---- …

feat: Add monitoring section

---

README.md

---
name: Add Photon Designer as tutorials source
about: Adding a link to Photon Designer as a tutorial in the Awesome Django list
title: "[NEW] Add link to Photon Designer Django tutorials"
assignees: ''
---
1. **Project Name:** Photon Designer tutorials
2. **Project URL:** https://photondesigner.com/articles
3. **Description:** The Photon Designer articles show how to build various Django apps as simply as possible
11 months
- 
4. **Are you the author or are you …

Add Photon Designer as tutorials source

---

README.md

Fixed wrong url. Feel a little embarred about that 🙈

Bugfix: Wrong url for django-pony-express

---

README.md

Django Cotton 
- https://github.com/wrabit/django-cotton
- https://django-cotton.com 
**Description:**
Cotton gives Django templates a new lease of life. It enables us to spin up UI's from truly modular and re-usable components. It overcomes [certain limitations](https://github.com/wrabit/django-cotton?tab=readme-ov-file#limitations-in-django-that-cotton-overcomes) that exist in Django template whilst increasing productivity with an expressive syntax.
----
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We …

Add Cotton

---

README.md

1. **Project Name:** Django Bridge
2. **Project URL:** https://github.com/django-bridge/django-bridge and https://django-bridge.org/
The simple way to build React frontends for Django applications
----
4 years as a closed source project, 6 months as open source
14 as an open source project (including pre-releases)
It's provides simpler way to build React frontends for Django, which is often overcomplicated when done manually. This library allows you to use regular Django views as a backend for a vanilla, standard …

Add Django Bridge

---

README.md

django-ckeditor is deprecated and uses CKEditor 4 which has unfixed security issues, it hasn't been a good recommendation for some time.
See the notice at the top of the README  https://github.com/django-ckeditor/django-ckeditor and the pinned issues here https://github.com/django-ckeditor/django-ckeditor/issues
EDIT: Sorry, I should clarify that I have deprecated django-ckeditor and that I have been doing all releases since May 2019. During the last few years I have been the sole active maintainer of the project.

Drop the django-ckeditor recommendation

---

README.md

1. **Project Name:** Wagtail events page
2. **Project URL:** https://wagtail.org/events/
The Events page is a recap of all Wagtail events – conferences for Wagtail users, contributor sprints, and online webinars. The Wagtail Space website is only the major conferences.
----
_(Please provide an approximate duration in months or years.)_ 10 years
_(Please provide the number of releases, or link to the project's release history.)_ Tens
The Events page is meant to be evergreen, with both upcoming events, and a history of …

Add Wagtail events page

---

README.md

1. **Project Name:** django-zeal
2. **Project URL:** https://github.com/taobojlen/django-zeal
django-zeal automatically detects N+1s with friendly error messages.
----
4-ish months
https://github.com/taobojlen/django-zeal/releases (10)
I spent a while looking for an existing library to do this. Unfortunately, the ones out there were unmaintained, didn't catch all types of N+1, slowed down your app, or were not very user-friendly. I wrote django-zeal to solve these problems!
----
The project is getting bug reports and …

add django-zeal

---

README.md

---
title: "htpy"
---
1. **Project Name:** htpy
2. **Project URL:** https://htpy.dev/
3. **Description:** htpy is a library that makes writing HTML in plain Python fun and efficient, without a template language.
----
1. **Is the …

Add templates htpy

---

README.md

#296 Since Awesome-Django already contains a project called Django-CRM, I used popular SEO keywords, hope this is ok.

Add Django-CRM built entirely on Django Admin Site

---

README.md

1. **Project Name:** django-admin-inline-paginator-plus
2. **Project URL:** https://github.com/DmytroLitvinov/django-admin-inline-paginator-plus
3. **Description:** ⏩ The "Django Admin Inline Paginator Plus" is simple way to paginate your inline in django admin
----
Please answer the following questions about the project you are submitting. This will help us determine whether it should be included in the Awesome Django list.
**Note:** If your project is only a few months old or has under 50 to 100 stars on GitHub, it may NOT meet the criteria for inclusion in the Awesome Django list. We recommend that you promote your project more and then consider submitting it when it has gained more visibility and community support.
**Additionally:** 🙅 We are not interested in Django Starter Kit …

feat: Add 'django-admin-inline-paginator-plus' to Admin section

---

README.md

This PR adds a new section to the README, Developer Tooling. I did the bare minimum mentioned in #320 and just moved the template formatting tools to a new subsection.
Open to suggestions on moving other packages to this new section -- I thought *maybe* testing related packages or the profiling tools could stand to be moved, but I'll leave that up to feedback.
closes #320

add new Developer Tooling section
